Repository SUSE-Cloud/automation, pull requests merged in 2018-10, with the labels that each got.

#2809 Use python3 for Leap 15 devstack jobs
  scripts/jenkins/qa_devstack.sh
Labels: wip

#2916 Remove old PTF repo during the upgrade so the new one can be added to zypp
  scripts/qa_crowbarsetup.sh
Labels: upgrade

#2913 ipv6: Catch virsh net-start errors
  scripts/lib/mkcloud-driver-libvirt.sh
Labels: IPv6-CP
