Repository SUSE-Cloud/automation, pull requests merged in 2019-07, with the labels that each got.

#3457 Cast bare variable to `bool`
  scripts/jenkins/cloud/ansible/roles/input_model_generator/tasks/main.yml
Labels: IPv6-CP

#3522 Configure git email for jenkins workers
  Makefile
  scripts/jenkins/workers/roles/jenkins_worker/files/gitconfig
  scripts/jenkins/workers/roles/jenkins_worker/tasks/configure_git.yml
  scripts/jenkins/workers/roles/jenkins_worker/tasks/main.yml
Labels: do not merge yet

#3527 openstack-maintenance-gating: add crowbar deploy jobs (SOC-9599,SOC-9669)
  jenkins/ci.suse.de/cloud-maintenance-gating.yaml
  jenkins/ci.suse.de/pipelines/cloud-gating-config.yml
  jenkins/ci.suse.de/pipelines/openstack-cloud.groovy
  jenkins/ci.suse.de/pipelines/openstack-maintenance-gating.Jenkinsfile
  scripts/jenkins/cloud/ansible/deploy-crowbar.yml
Labels: do not merge yet

#3442 Remove ssh host key of admin FIP
  scripts/jenkins/cloud/ansible/roles/ssh_keys/tasks/main.yml
  scripts/jenkins/cloud/ansible/setup-ssh-access.yml
  scripts/jenkins/cloud/manual/input.yml.example
Labels: IPv6-CP, cloud-networking, enhancement

#3538 Fix spelling
  scripts/jenkins/cloud/ansible/bootstrap-vcloud-nodes.yml
Labels: bug, cloud-networking

#3539 Replace `wait_for_connection` with `wait_for`
  scripts/jenkins/cloud/ansible/setup-ssh-access.yml
Labels: cloud-networking

#3540 Add the correct IPv6 settings to the management subnet
  scripts/jenkins/cloud/ansible/roles/heat-generator/templates/heat-template.yaml
Labels: IPv6-CP, cloud-networking

#3560 maintenance gating: add Crowbar update jobs to maintenance gating (SOC-9797,SOC-9798)
  jenkins/ci.suse.de/cloud-ardana8.yaml
  jenkins/ci.suse.de/cloud-ardana9.yaml
  jenkins/ci.suse.de/cloud-maintenance-gating.yaml
  jenkins/ci.suse.de/cloud-maintenance.yaml
  jenkins/ci.suse.de/pipelines/cloud-maintenance-gating-config.yml
  jenkins/ci.suse.de/pipelines/cloud-maintenance-gating.Jenkinsfile
Labels: do not merge yet

#3554 Create the local ssh key in the right directory
  scripts/jenkins/cloud/ansible/roles/ssh_keys/tasks/main.yml
Labels: bug
