Repository SUSE-Cloud/automation, pull requests merged in 2019-01, with the labels that each got.

#2938 upgrade-scale: basic deployment scenario files and setup script
  hostscripts/gatehost/crowbaru1.xml
  hostscripts/upgrade-scale/README.md
  hostscripts/upgrade-scale/batches/00_provisioner.yml
  hostscripts/upgrade-scale/batches/01_ipmi.yml
  hostscripts/upgrade-scale/batches/02_ntp.yml
  hostscripts/upgrade-scale/batches/03_pacemaker.yml
  hostscripts/upgrade-scale/batches/04_database.yml
  hostscripts/upgrade-scale/batches/05_rabbitmq.yml
  hostscripts/upgrade-scale/batches/06a_keystone.yml
  hostscripts/upgrade-scale/batches/06b_keystone.yml
  hostscripts/upgrade-scale/batches/07_monasca.yml
  hostscripts/upgrade-scale/batches/08_ceph.yml
  hostscripts/upgrade-scale/batches/09_glance.yml
  hostscripts/upgrade-scale/batches/10_cinder.yml
  hostscripts/upgrade-scale/batches/11_neutron.yml
  hostscripts/upgrade-scale/batches/12_nova.yml
  hostscripts/upgrade-scale/batches/13_horizon.yml
  hostscripts/upgrade-scale/batches/14_heat.yml
  hostscripts/upgrade-scale/batches/15_manila.yml
  hostscripts/upgrade-scale/setup.sh
  scripts/lib/mkcloud-onhost.sh
  scripts/qa_crowbarsetup.sh
Labels: upgrade

#3052 Update local ipv6 address to use fd::/64.
  scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/networks.yml
  scripts/jenkins/ardana/ansible/roles/input_model_generator/templates/input_model/data/neutron/neutron_config.yml
Labels: IPv6-CP

#2879 ipv6: first attempt at want_ipv6 option
  scripts/lib/ipv6/network.json
  scripts/lib/mkcloud-common.sh
  scripts/lib/mkcloud-driver-libvirt.sh
  scripts/lib/mkcloud-onhost.sh
  scripts/mkcloud
  scripts/qa_crowbarsetup.sh
Labels: IPv6-CP

#3037 Localize variables used in `addfloatingip`
  scripts/qa_crowbarsetup.sh
Labels: IPv6-CP, bug

#3067 mkcloud: Teach setupadmin about ping6
  scripts/mkcloud
Labels: IPv6-CP

#3089 Add basic jobs for SOC8-SOC9 upgrade
  jenkins/ci.suse.de/cloud-mkcloud9.yaml
Labels: upgrade

#3063 ipv6: Add network details to routed.cloud
  scripts/mkcloudhost/routed.cloud
Labels: IPv6-CP

#3128 Set default for `want_ipv6`
  scripts/mkcloudhost/routed.cloud
Labels: bug
