Repository SUSE-Cloud/automation, pull requests merged in 2019-05, with the labels that each got.

#3387 openstack-ardana-gerrit: re-enable cert verification
  scripts/jenkins/ardana/gerrit/gerrit.py
Labels: do not merge yet

#3405 Use `items()` instead of `iteritems()`
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/load_input_model.py
Labels: bug

#3399 Make sure the Python venv is using Python 2
  scripts/jenkins/ardana/manual/lib.sh
Labels: bug

#3421 Convert `dict_view` into `list` for Python3
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
Labels: IPv6-CP, Python3

#3411 Replace deprecated `Exception.message`
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/load_input_model.py
Labels: IPv6-CP, Python3

#3414 Replace `filter` with equivalent `six.moves.filter`
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
Labels: IPv6-CP, Python3

#3410 Replace `iteritems` with `items`
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
Labels: IPv6-CP, Python3, bug

#3424 Convert `print` to function call for Python 3
  scripts/jenkins/jenkins-job-pipeline-report.py
Labels: IPv6-CP, Python3

#3345 ipv6: Configure radvd if required during prepare
  scripts/lib/ipv6/radvd-conf-template
  scripts/lib/mkcloud-driver-libvirt.sh
  scripts/mkcloudhost/generate-radvd-conf
Labels: IPv6-CP

#3432 Split Heat stack deploy into separate function
  scripts/jenkins/ardana/manual/lib.sh
Labels: IPv6-CP

#3433 socok8s: Deploy with airship and osh for PRs
  jenkins/ci.suse.de/cloud-socok8s.yaml
  jenkins/ci.suse.de/templates/cloud-socok8s-integration.yaml
Labels: do not merge yet

#3412 Remove `input.yml` from git
  scripts/jenkins/ardana/manual/input.yml.example
Labels: IPv6-CP, Python3

#3439 For debugging, print a traceback on Exception
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/generate_heat_model.py
  scripts/jenkins/ardana/ansible/roles/heat-generator/library/load_input_model.py
Labels: IPv6-CP

#3431 Split generate-heat-template step for debugging
  scripts/jenkins/ardana/manual/lib.sh
Labels: IPv6-CP

#3440 Make `bootstrap-crowbar` idempotent
  scripts/jenkins/ardana/ansible/bootstrap-crowbar.yml
Labels: IPv6-CP, bug

#3419 Add environment variable to add arguments to Ansible
  scripts/jenkins/ardana/manual/lib.sh
Labels: IPv6-CP, Python3

#3460 Fix bashate errors
  .dir-locals.el
  scripts/jenkins/ardana/manual/lib.sh
Labels: IPv6-CP
