Repository SUSE-Cloud/automation, pull requests merged in 2019-06, with the labels that each got.

#3441 Make `bootstrap-crowbar-nodes` idempotent
  scripts/jenkins/ardana/ansible/bootstrap-crowbar-nodes.yml
Labels: IPv6-CP, bug

#3464 Fix incorrect type in dir locals file
  .dir-locals.el
Labels: IPv6-CP

#3420 Replace `itervalues()` method with `six` equivalent
  scripts/jenkins/cloud/ansible/roles/heat-generator/library/generate_heat_model.py
Labels: IPv6-CP, Python3

#3451 Move DNS update script into template
  scripts/jenkins/cloud/ansible/roles/heat-generator/library/dns_update.py
  scripts/jenkins/cloud/ansible/roles/heat-generator/tasks/main.yml
Labels: IPv6-CP

#3492 openstack-ardana: run manila tempest tests on gating jobs
  jenkins/ci.suse.de/cloud-ardana8.yaml
  jenkins/ci.suse.de/cloud-ardana9.yaml
Labels: do not merge yet

#3458 Update `delegate_to` for Ansible 2.8
  scripts/jenkins/cloud/ansible/bootstrap-crowbar-nodes.yml
  scripts/jenkins/cloud/ansible/bootstrap-vcloud-nodes.yml
  scripts/jenkins/cloud/ansible/register-crowbar-nodes.yml
Labels: IPv6-CP, bug

#3501 Remove obsoleted task
  scripts/jenkins/cloud/ansible/bootstrap-crowbar.yml
Labels: IPv6-CP
