Repository SUSE-Cloud/automation, pull requests merged in 2020-01, with the labels that each got.

#3803 Add Octavia to SOC9 mkcloud jobs (SOC-10685)
  jenkins/ci.suse.de/cloud-mkcloud9.yaml
  jenkins/ci.suse.de/openstack-mkcloud.yaml
  jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-tempestfull-template.yaml
  jenkins/ci.suse.de/templates/cloud-mkcloud-job-4nodes-linuxbridge-template.yaml
  jenkins/ci.suse.de/templates/cloud-mkcloud-job-dvr-template.yaml
  jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-compute-template.yaml
  jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-bonding-template.yaml
  jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-linuxbridge-template.yaml
  jenkins/ci.suse.de/templates/cloud-mkcloud-job-ha-template.yaml
  scripts/mkcloud
Labels: do not merge yet

#3814 Set the values of want_cloud*_iso also for the upgrade_cloudsource
  scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2
Labels: upgrade

#3792 upgrade: Add support for multiple upgrade test stacks
  scripts/heat/2-instances-cinder.yaml
  scripts/mkcloud
  scripts/qa_crowbarsetup.sh
Labels: upgrade

#3651 Increase debug output for OpenStack components
  jenkins/ci.suse.de/templates/cloud-crowbar-pipeline-template.yaml
  scripts/jenkins/cloud/ansible/roles/cloud_generator/templates/mkcloud.config.j2
Labels: enhancement
